services:
  mud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mud
    volumes:
      - ./log:/opt/rom/log:rw
      - ./player:/opt/rom/player:rw
      - ./gods:/opt/rom/gods:rw
      - ./area:/opt/rom/area:rw
    ports:
      - 4000:4000
