#!/bin/bash
# Written by Furey.
# With additions from Tony and Alander.
# Adapted to Bash by SirLouen

port=4000
if [ ! -z "$1" ]; then
    port="$1"
fi

# Set limits.
if [ -e shutdown.txt ]; then
    rm -f shutdown.txt
fi

while true; do
    # If you want to have logs in a different directory,
    #   change the 'logfile' line to reflect the directory name.
    index=1000
    while true; do
        logfile="../log/${index}.log"
        if [ ! -e "$logfile" ]; then
            break
        fi
        ((index++))
    done

    # Run rom.
    ./rom "$port" > "$logfile" 2>&1

    # Restart, giving old connections a chance to die.
    if [ -e shutdown.txt ]; then
        rm -f shutdown.txt
        exit 0
    fi
    sleep 10
done